### ISSUE TITLE
Gap at standstill (minGap) for ACC/CACC

### ISSUE THREAD

**Issue by 1010617348** [eclipse-sumo/sumo#13920] opened 2023-10-09 07:40 UTC
During the simulation, I noticed that when the CACC vehicle is behind the ACC vehicle, the ACC vehicle is behind the ACC vehicle, and the ACC vehicle is behind the IDM vehicle, the distance between the rear car and the front car at rest is is different from the set parameter minGap. This problem does not occur when IDMs follow other types of vehicles and CACC follow CACC. Why?

**SUMO-version:Git version**

**operating system:windows10**

**Comment by robertalms** [comment] 2023-10-09 18:58
The ACC and CACC models have a so-called "dynamic spacing margin", that adds up to `2m` for standstill situations on top of the `minGap`. Have a look at the respective publication No. 2 from Xiao et al., 2017 cited in the SUMO documenation: [ACC](https://sumo.dlr.de/docs/Car-Following-Models/ACC.html#references)

**Comment by 1010617348** [comment] 2023-10-10 00:51
> The ACC and CACC models have a so-called "dynamic spacing margin", that adds up to `2m` for standstill situations on top of the `minGap`. Have a look at the respective publication No. 2 from Xiao et al., 2017 cited in the SUMO documenation: [ACC](https://sumo.dlr.de/docs/Car-Following-Models/ACC.html#references)

I notice that in this article, the premise for setting the Dynamic Spacing Margin is that the desired gap between vehicles at standstill is zero, whereas in the sumo simulation, this gap is "minGap" instead of 0. Does this part need to be corrected?

**Comment by 1010617348** [comment] 2023-10-10 01:51
In addition, why do CACC and ACC take dynamic spacing margin when they follow ACC, but CACCs don't take dynamic spacing margin when they follow CACC?

**Comment by robertalms** [comment] 2023-10-10 08:09
> In addition, why do CACC and ACC take dynamic spacing margin when they follow ACC, but CACCs don't take dynamic spacing margin when they follow CACC?

It's simply not implemented yet for the CACC due to time constraints. The gap closing behaviour of the CACC model is quite delicate (cf. [11679](https://github.com/eclipse-sumo/sumo/issues/11679)) and needs a more indepth analysis before altering the code, we couldn't manage so far.

> I notice that in this article, the premise for setting the Dynamic Spacing Margin is that the desired gap between vehicles at standstill is zero, whereas in the sumo simulation, this gap is "minGap" instead of 0. Does this part need to be corrected?

This is by design. The ACC model in SUMO doesn't aim to be a plain vanilla ACC model because it tries to ensure crash safety in simulations as best as possible - see also modes (iii) and (iv) in [ACC](https://sumo.dlr.de/docs/Car-Following-Models/ACC.html). Eliminating the minGap concept in SUMO from the model would result in various crash and warning issues without handling these properly. We don't have the ressources at the moment to provide a more flexible code base to account for such a ACC option.

**Closed** 2023-10-10 08:25 UTC
Labels: a:sumo, c:carfollow
