### ISSUE TITLE
CO2 emissions inconsistency edges vs. vehicles

### ISSUE THREAD

**Issue by GiulianoCornacchia** [eclipse-sumo/sumo#14209] opened 2024-01-05 16:55 UTC
**Issue description:**

I am working on computing CO2 emissions for each edge and the overall emissions per vehicle in my simulation. To achieve this, I am utilizing the Edge-Based Emission Output for emissions on the edges, along with the SUMO option `--device.emissions.probability 1 --tripinfo-output` to determine the emission levels from each vehicle.

However, I have encountered an inconsistency where the sum of CO2 emissions on each edge does not align with the total CO2 emissions from each vehicle, except in cases where the vehicle route consists of only one edge.

Expected behavior dictates that the sum of CO2 on each edge should precisely match the total CO2 emissions from all vehicles. Yet, this alignment is not occurring in scenarios beyond single-edge routes.

How can I fix this issue, and which of the two sums (CO2 on each edge vs. total CO2 emissions per vehicle) should be considered as the correct one?

*Example that shows the problem.*: 
Download the folder with the files to replicate the issue [here](https://drive.google.com/file/d/1oGcwuc6XVDb7Faybv5_ZH-SerEZZCiRa/view?usp=sharing).
Run the pyhton notebook `CO2_check.ipynb` to replicate the issue.

**SUMO-version:** 1.19.0

**operating system:** Windows 10

Thanks.

**Comment by m-kro** [comment] 2024-01-08 10:57
You are right that in the real world, both numbers should match exactly. The problem arises probably from some discretisation and time step order issues. 

The emissions are computed at discrete time steps given the vehicle state at that point in time. As the EdgeData should only take into account emissions attributable to the referenced edge, the time step share the vehicle was on the edge is estimated. The emission device doesn't have to care about edges and just uses the whole time step length as weight factor. 

I didn't check this in detail yet, but the used speeds and their time-based weights are very probably the reason for the differences between the output options.

**Comment by GiulianoCornacchia** [comment] 2024-01-10 10:55
Thank you for the detailed explanation. It makes sense that the differences could be related to discretization and time step length.

If there are specific tests or checks you recommend performing to narrow down the problem, I would be happy to carry them out. 

Thanks again!

**Comment by behrisch** [comment] 2024-01-18 12:48
The problem is actually not the time stepping but the overlap of the vehicle with multiple edges. Currently the emission produced is assigned to every edge the vehicle overlaps with. So if you sum over all edges, double or even triple counts can occur. This gets worse the longer the vehicle is. I think we should change this and only count the emission for the edge the front of the vehicle is on (maybe with an option to trigger the old behavior). Although the emissions leave the vehicle at the back most of time, the front is more in line with what the position of the vehicle reports.

**Comment by m-kro** [comment] 2024-01-22 09:58
@GiulianoCornacchia We have changed the weights for edgeData emission output. Previously we used the time a part of the vehicle was on the edge, now it is time the vehicle front was on the edge. Our previous approach was wrong because the same emissions could be assigned to more than one edge / the weights would not necessarily sum up to 100%.

Running your scenario with the new weight reduces the difference to the emissions device stats by approx. 90%.

**Closed** 2024-01-22 10:36 UTC
Labels: a:sumo, bug, c:emissions
