### ISSUE TITLE
meso: temporarily change the capacity (e.g., close or slow down traffic) of a certain lane (or a certain cell)

### ISSUE THREAD

**Issue by xingminw** [eclipse-sumo/sumo#14538] opened 2024-03-18 21:32 UTC
I am working on sumo meso simulation.

What I want to to use Traci to slow down (even stop) some of the vehicles. However, it seems that many of the vehicle-level change states in meso mode do not work (I have tested functions like slowdown, setstop, moveto, etc.)

I am wondering what is the best way to at least mimic this effect. How can I temporarily change the capacity of a certain lane in meso mode? I understand that in meso mode, sumo works like splitting roadways into different cells according to a predetermined resolution. I am particularly curious how can I manipulate the capacity of given cells (for example, shuts down some of the cells in a certain lane for a while). 

I think this is very useful and should be easy since it is something like a temporary red light at a certain location. 

In micro mode, this can be easily done by putting a stopped vehicle, however, I have tried many different methods in meso but could not find one easy way yet.

**Comment by xingminw** [comment] 2024-03-18 21:58
The other thing is that I do not want to slow down the whole lane but put some restrictions at the exit of the lane (put a maximum flow constraint).

**Comment by xingminw** [comment] 2024-03-19 13:42
I have also tried `traci.lane.setMaxSpeed()`. What I did was to set the max speed to zero for a while and set it back to the normal speed limit. However, it only worked when I set it to 0 and it did not come back to normal. 

The other question is, can I just perform a manipulation on a more detailed resolution? In meso mode, the road way is split into different cells/segments, what if I just want to slow down one of the segments?

Thank you for your help. I appreciate it.

**Comment by xingminw** [comment] 2024-03-19 13:45
For the potential issue with lane level `setMaxSpeed()`, I can share the example afterward.

**Comment by namdre** [comment] 2024-03-19 15:11
The current architecture for meso support any access to segments via TraCI and they don't have any internal state that could hold a custom segment speed (it's all taking from the parent edge). It should actuallly be possible to stop a meso vehicle and have it clog up a lane. They tricky part is that you must define a stop for a segment the vehicle hasn't reached yet (by stopping on some future edge or at least a large enough position along the same edge so that it's on another segment.

If you can give a small example for how setMaxSpeed doesn't reset, that would be nice.

**Comment by xingminw** [comment] 2024-03-19 19:32
The network topology is as simple as a E0 upstream edge connects to a downstream E2 edge:
E0 (around 500 meters) -----> E2 (around 200 meters).

I just performed a simple test to set speed of all lanes in E2 to be zero for 50 secs. The following is the code within each simulation step:
```python
while traci.simulation.getMinExpectedNumber() > 0:
    if timestep == 250:
        traci.lane.setMaxSpeed("E2_0", 0)
        traci.lane.setMaxSpeed("E2_1", 0)
        traci.lane.setMaxSpeed("E2_2", 0)
    if timestep == 300:
        traci.lane.setMaxSpeed("E2_0", 20)
        traci.lane.setMaxSpeed("E2_1", 20)
        traci.lane.setMaxSpeed("E2_2", 20)
    timestep += 1
    traci.simulationStep()
```

Results of meso (I plotted the trajectories in the time-space diagram):
![image](https://github.com/eclipse-sumo/sumo/assets/44205791/69238f9e-fe34-4be6-bc54-b3760af3b042)

Results of micro:
![image](https://github.com/eclipse-sumo/sumo/assets/44205791/3d7e2725-dca4-4071-a490-575630ab32db)

The configuration file is exactly the same for micro and meso except for I turned on/off the meso mode.

You can clearly see that, in micro mode, the downstream edge is able to recover to normal while the meso did not come back.

**Comment by xingminw** [comment] 2024-03-19 19:39
Does this mean that we can manipulate a certain segment within the edge through traci? This would be very useful for many applications. 

Could you please indicate more how I can achieve a similar effect like stopping or slowing down a vehicle in the middle of an edge? In meso mode, I believe a segement-level manipulation would be sufficient. It does not need to be the vehicle-level. My issue would be completely resolved if I can control the speed or maximum outflow of a certain segment within an edge. Once again, I really appreciate your help and reply. 

> The current architecture for meso support any access to segments via TraCI and they don't have any internal state that could hold a custom segment speed (it's all taking from the parent edge). It should actuallly be possible to stop a meso vehicle and have it clog up a lane. They tricky part is that you must define a stop for a segment the vehicle hasn't reached yet (by stopping on some future edge or at least a large enough position along the same edge so that it's on another segment.
> 
> If you can give a small example for how setMaxSpeed doesn't reset, that would be nice.

**Comment by namdre** [comment] 2024-03-20 07:24
meso edge speed recovery is now fixed in the dev version

**Comment by xingminw** [comment] 2024-03-20 14:10
Thank you for your timely response and quick action. 

I have two follow-up questions and I hope they won't bother you too much. 

1. Is the main branch the dev version you refer to or some other branch? I saw that the commit has been merged to the main. If you can indicate the branch that has fixed this issue, I can also do a further test on my end. 
2. I am wondering whether there is a way to perform segment-level manipulation as I mentioned before. With this `edge.setMaxSpeed` being fixed, I can slow down or stop the whole traffic in the lane but it would be better that there is method to only set certain segments to stop or a lower speed.

Thank you again for your help. It is much appreciated.

**Comment by xingminw** [comment] 2024-03-20 15:26
Thank you. 
For the second question, I have tested multiple functions before to control the vehicles (slowdown, setstop, moveto, etc.). However, it seems that currently, they do not work. Could you please let me know what is the best way if I want to control individual vehicles? I thought in meso mode, vehicles were not controllable.

**Comment by namdre** [comment] 2024-03-20 15:32
setStop and insertStop should work for meso. Just make sure that new stop is far enough upstream.

**Comment by xingminw** [comment] 2024-03-21 02:17
Thank you for the suggestion and I finally made `setStop` work. 

However, for the `lane.setMaxSpeed`, I still find some issues. I have downloaded and installed the nightly version `March 20 2024 23:11:16 UTC ` (which I think the changes have been applied). 

Here are the new results I got:

The micro is still correct which can be used as a benchmark:
![image](https://github.com/eclipse-sumo/sumo/assets/44205791/861552ee-b565-4cc4-a6d5-036abfb930b9)

For meso, if I use the `edge.setMaxSpeed` with the following code:
```python
    if timestep == 250:
        traci.edge.setMaxSpeed("E2", 0)
    if timestep == 300:
        traci.edge.setMaxSpeed("E2", 20)
```

here is the new result:
![image](https://github.com/eclipse-sumo/sumo/assets/44205791/8d7de808-2619-451c-b4e7-94ef31411c1a)
which seems correct now! If I remember correctly, this does not work before.

However, if I use the `lane.setMaxSpeed` with the following code:
```python
    if timestep == 250:
        traci.lane.setMaxSpeed("E2_0", 0)
        traci.lane.setMaxSpeed("E2_1", 0)
        traci.lane.setMaxSpeed("E2_2", 0)
    if timestep == 300:
        traci.lane.setMaxSpeed("E2_0", 20)
        traci.lane.setMaxSpeed("E2_1", 20)
        traci.lane.setMaxSpeed("E2_2", 20)
```
We still have the issue before. 
![image](https://github.com/eclipse-sumo/sumo/assets/44205791/347b5633-46f5-4de4-a787-594bbded5bd9)

Therefore, it seems that the `edge.setMaxSpeed` has been fixed but `lane.setMaxSpeed` still does not work as expected. Hope this would help. Thank you again for your response.

**Comment by namdre** [comment] 2024-03-21 06:49
Thanks for the careful analysis. It will be fixed in the nightly version available tomorrow.

**Comment by xingminw** [comment] 2024-03-24 03:03
Thank you. I think the specific issue has been resolved: the vehicle now can recover to normal speed once the lane speed is set back to normal.

I hope this will not bother you but I have another follow-up question associated with one more potential issue:
I am wondering whether the meso and Traci can support lane-level manipulation: through a simple test, I noticed that once I set the parameter for just a single lane, it will be applied to the entire segment it belongs to. For example, one line `traci.lane.setMaxSpeed("E2_0", 0)` would stop the entire segment. Is this a bug or just what it is for the current version?
In many cases, we might need to close one out of multiple lanes but currently, it is not achievable.

**Comment by namdre** [comment] 2024-03-24 09:04
That was the expected behavior earlier. After the latest fix, lane.setMaxSpeed only affects a single queue when running with option **--mes-multi-queue**. (see #14589)

**Comment by xingminw** [comment] 2024-03-25 00:13
Through the simple case I just tested, it did not seem to work according to your description.

Version: nightly `March 24 2024 23:11:09 UTC`
Test scenario: 3 lanes E0 connects to a downstream 3 lanes E2. 
I also set the following in the configuration file:
```html
<meso-multi-queue value="true"/>
<meso-lane-queue value="true"/>
```

In the code, I set one out of three lanes to 0 speed:
```python
  if timestep == 250:
      traci.lane.setMaxSpeed("E2_0", 0)
```

According to your description, this should only close one lane. However, the result indicated that all lanes were shutdown. 
![image](https://github.com/eclipse-sumo/sumo/assets/44205791/e9acde2a-abc0-4dd5-80c0-2a5842fe5efd)

I also did other tests showing similar, making me feel that the lane.setMaxSpeed() still change the parameter of the segment.

Please let me know if I did anything wrong.

By the way, thank you again for your timely response even over the weekend. I am willing to perform further tests if you make any further changes. I am a transportation researcher working on traffic flow theory and am more than glad if I can make any contributions to SUMO meso.

**Comment by namdre** [comment] 2024-03-25 14:35
The speeds that you probably used as the basis for your plot were wrong (based on the speed limit of lane 0 rather than the actual queue being used).
Note, that speeds in meso fcd output are not reliable when the speed limit changes while a vehicle is already on the lane since they are just based on segment entry and projected exit time ('ts not a microscopic model after all).

**Comment by xingminw** [comment] 2024-03-25 14:40
I did not use speed to plot the figure but the location of each vehicle at each time. I understand that the zigzag of the trajectory is caused by the spatial discretization. 

I am wondering why all vehicles stop even though I just set 1 out of 3 downstream lanes to be closed (0 max speed).
What I expect is that with 1 out of 3 lanes closed, vehicles should use the other two lanes to enter the downstream edge.

**Comment by xingminw** [comment] 2024-03-26 03:29
Hi, I ran the code again based on the latest nightly version (`March 25 2024 04:21:35 UTC`).

It seems that the issue is "partially fixed".  The following is the latest results:

The test case is still upstream edge connects to the downstream edge and both have three lanes. The Blue dashed line is the boundary. I set the speed limit for one of the downstream lanes to be zero at t=250 (red dashed line).

![image](https://github.com/eclipse-sumo/sumo/assets/44205791/062e926b-5149-4ea2-8b30-0998cfa0a90f)

My interpretation and guess of this new result is that: it might successfully set one of the downstream lanes to have a max speed of zero since we can now see some vehicles are able to keep going to the downstream edge. 
However, there are some vehicles that suddenly stop on the downstream road (which I do not think is a reasonable outcome). Is it because some vehicles somehow enter the closed lane and are trapped in it?
I understand this might lead to another issue related to the choice of lane & lane-level queue model. If you think this issue is beyond the scope of our current discussion, you can close this issue. I can also open a new issue if you have interest to further fix it. I am willing to test more.

**Comment by namdre** [comment] 2024-03-26 08:42
Yes. you are right. Some vehicles become "trapped" in the low speed queue. As you rightly guess this opens up the topic of lane choice for meso which doesn't consider speed limits at the moment (could be a new ticket). If you wish to close one of multiple lanes you could instead call `lane.setDisallowed(laneID, "all")` as this doesn't trap vehicles.

**Closed by namdre** 2024-03-26 08:42 UTC
Labels: question, c:meso
