### ISSUE TITLE
How to get acceptedBadges of parking area from Traci?

### ISSUE THREAD

**Issue by sean-reed** [eclipse-sumo/sumo#15464] opened 2024-09-10 13:37 UTC
Is there a way to get the value of the acceptedBadges parameter of a parking area through Traci? I tried traci.parkingArea.getParameter(pa_id, "acceptedBadges") but it did not return anything.

**Comment by m-kro** [comment] 2024-09-16 10:56
Related to #14807

**Comment by m-kro** [comment] 2024-10-24 13:29
Actually a duplicate of #14807

**Closed by m-kro** 2024-10-24 13:29 UTC
Labels: duplicate, enhancement, a:sumo, c:traci
