### ISSUE TITLE
libsumo does not work on M1 mac

### ISSUE THREAD

**Issue by ashok-arora** [eclipse-sumo/sumo#13097] opened 2023-04-21 18:21 UTC
Here's the output for the import command.
```
Python 3.10.9 (main, Jan 11 2023, 09:18:18) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ashok/miniconda/lib/python3.10/site-packages/libsumo/__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight  # noqa
  File "/Users/ashok/miniconda/lib/python3.10/site-packages/libsumo/libsumo.py", line 13, in <module>
    from . import _libsumo
ImportError: dlopen(/Users/ashok/miniconda/lib/python3.10/site-packages/libsumo/_libsumo.so, 0x0002): tried: '/Users/ashok/miniconda/lib/python3.10/site-packages/libsumo/_libsumo.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ashok/miniconda/lib/python3.10/site-packages/libsumo/_libsumo.so' (no such file), '/Users/ashok/miniconda/lib/python3.10/site-packages/libsumo/_libsumo.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**SUMO-version:** 1.15.0

**operating system:** macOS Ventura 13.0.1

**Comment by behrisch** [comment] 2023-04-21 21:12
@ashok-arora Can you please try whether it fails with a plain python as well? We sometimes encountered problems with anaconda because it ships its own libraries

**Comment by ashok-arora** [comment] 2023-04-21 23:27
@behrisch Yes, it seems to be a problem with Homebrew python as well. 
```
↪ python3
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/libsumo/__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight  # noqa
  File "/opt/homebrew/lib/python3.10/site-packages/libsumo/libsumo.py", line 13, in <module>
    from . import _libsumo
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/libsumo/_libsumo.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/libsumo/_libsumo.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/libsumo/_libsumo.so' (no such file), '/opt/homebrew/lib/python3.10/site-packages/libsumo/_libsumo.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by ashok-arora** [comment] 2023-04-28 21:09
@behrisch I had installed it using `pip` by following the documentation given [here].(https://sumo.dlr.de/docs/Downloads.php#python_packages_virtual_environments)

**Comment by ashok-arora** [comment] 2023-05-03 23:13
@behrisch, @angelobanse any updates on this?

**Comment by ashok-arora** [comment] 2023-06-03 07:08
@behrisch, @angelobanse?

**Comment by namdre** [comment] 2023-06-03 11:54
@palvarezlopez could you give a clue here?

**Comment by behrisch** [comment] 2023-06-03 18:56
I just tried it again on our M1 mac and it works like a charm for 1.17.0. I could not find a libsumo version 1.15.0 for M1 though. Can you please post the precise commands you used to install it and also the output of pip?

**Comment by behrisch** [comment] 2023-09-21 05:30
Closing for lack of reproducability. Please leave another comment if the problem persists and we will reopen.

**Closed by behrisch** 2023-09-21 05:30 UTC
Labels: c:build, c:libsumo, awaiting reply
