### ISSUE TITLE
Taxi leaves simulation while using randomCircling

### ISSUE THREAD

**Issue by rklshbl** [eclipse-sumo/sumo#8423] opened 2021-03-25 14:37 UTC
In the scenario dropOff, using the randomCircling behavior the taxi is assigned a passenger (p_7). The warning that no stop for a drop off could be added appears but the taxi picks up the pedestrian anyway. Right after the pedestrian is picked up however, the taxi and passenger leave the simulation. 

In the scneario pickup, using the randomCircling behavior a pedestrian (p_6) is waiting at a busStop for pickup when the warning that no stop for the pickup could be added appears. The taxi doesnt pick the pedestrian up, however it drives to the pedestrians destination and behaves like it has a passenger. After the 'drop off' the taxi continues but doesn't pick up any passengers and leaves the simulation shortly after.

From what i could observe, these warnings appear when the taxi is on a node.
[Scenario_dropOff.zip](https://github.com/eclipse/sumo/files/6205465/Scenario_dropOff.zip)
[Scenario_pickup.zip](https://github.com/eclipse/sumo/files/6205466/Scenario_pickup.zip)

**Comment by namdre** [comment] 2021-03-25 21:29
Thanks for the well-prepared examples! (Note, that I'm not adding a regression test for Scenario_pickup because the bug for rerouting on a junction is a duplicate of #8398)

**Closed by namdre** 2021-03-25 21:29 UTC
Labels: a:sumo, c:taxi
