### ISSUE TITLE
Parking rerouter does not reroute occupants

### ISSUE THREAD

**Issue by sean-reed** [eclipse-sumo/sumo#15276] opened 2024-07-24 14:46 UTC
When people ride a vehicle to a car park and that vehicle is rerouted to another car park, due to the original destination car park being full, the occupants teleport to the edge of the original car park destination on arrival at the rerouted car park. It would be more realistic if the occupants were rerouted along with car they are riding in. 

I have attached an example that illustrates this. Here the second car, carrying the blue colored person, is rerouted from the north to the south car park. When the car parks at the south car park, the occupant teleports to the edge where the north car park is located and continues their trip.

SUMO 1.20.0
Windows 11

[parking-test.zip](https://github.com/user-attachments/files/16363794/parking-test.zip)

**Comment by namdre** [comment] 2024-07-31 09:56
The problem is fixed in 1.21.0 (likely as a side effect of some other bugfix).  However, we still don't have a lot of tests for rerouting of riders so please bring up anything else you find.

**Closed by namdre** 2024-07-31 09:56 UTC
Labels: a:sumo, bug
