### ISSUE TITLE
add vClass "Cable car"

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#11720] opened 2022-09-28 08:11 UTC
As suggested on monday by users at the UNAM talk.

**Comment by namdre** [comment] 2022-09-28 11:01
I don't think this is needed and you could simply use rail_urban. 
Different vehicle classes are only needed if the networks are connected (i.e. to prevent a train from driving on a cable) but this should never be an issue for cable cars. 

- a gui-shape for cable cars might be useful
- a distinct drawing style for the cables would be nice though.  Since adding a new vehicle class has lots of compatibility effects I'd first try to come up with another solution that is more lightweight (i.e. configuring width=0.1 for the edges).

**Comment by behrisch** [comment] 2022-09-29 09:17
There might also be issues like assigning stops to lines which sometimes check for permissions but in general I agree with @namdre: Inventing a new vclass is too much for this probably rather small use case.

**Comment by angelobanse** [comment] 2022-10-10 09:09
https://en.wikipedia.org/wiki/Mexicable
https://en.wikipedia.org/wiki/Metrocable_(Medell%C3%ADn)

**Comment by namdre** [comment] 2022-10-14 07:00
more reason for adding a new vClass
- **connection computation is different, cable cars may turn a tight corner whereas trains cannot** 
- configuring a small lane width is bad because aerialways default to two-way and need sufficient spacing between them (which is derived from the width

**Comment by namdre** [comment] 2024-02-28 13:33
duplicate of #12335

**Closed by namdre** 2024-02-28 13:33 UTC
Labels: enhancement, sumo-user
