### ISSUE TITLE
what's the meaning of duation in setAcceleration()

### ISSUE THREAD

**Issue by nobugforerer** [eclipse-sumo/sumo#14660] opened 2024-04-04 05:39 UTC
While i set duation as 1.00, in the next step the velocity increases only the half of the acceleration

**Comment by namdre** [comment] 2024-04-04 06:03
duplicate of #7361 (setAcceleration uses `slowDown` in the background)

**Closed by namdre** 2024-04-04 06:03 UTC
Labels: duplicate

**Comment by namdre** [comment] 2025-02-13 08:16
it's fixed now.
