### ISSUE TITLE
Ubuntu 20.04 compilation error

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse-sumo/sumo#15204] opened 2024-07-13 14:33 UTC
Hello, sumo developer，I have a problem compiling SUMO，these are my steps

sudo apt-get install cmake python g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev swig
cd ~/sumo
export SUMO_HOME="$PWD"
mkdir build/cmake-build && cd build/cmake-build
cmake ../..
make -j$(nproc)
But an error was reported：
[ 99%] Linking CXX executable ../../../../../../bin/testgeom
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint8@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_closure_loc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_pointer@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint64@LIBFFI_BASE_7.0'
/usr/bin/ld: /root/anaconda3/lib/libgtest.so.1.11.0: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_closure_alloc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_cif@LIBFFI_BASE_7.0'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/src/utils/common/CMakeFiles/testcommon.dir/build.make:162: ../../bin/testcommon] Error 1
make[1]: *** [CMakeFiles/Makefile2:5449: unittest/src/utils/common/CMakeFiles/testcommon.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint8@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_closure_loc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_pointer@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint64@LIBFFI_BASE_7.0'
/usr/bin/ld: /root/anaconda3/lib/libgtest.so.1.11.0: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_closure_alloc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_cif@LIBFFI_BASE_7.0'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/src/utils/geom/CMakeFiles/testgeom.dir/build.make:146: ../../bin/testgeom] Error 1
make[1]: *** [CMakeFiles/Makefile2:5488: unittest/src/utils/geom/CMakeFiles/testgeom.dir/all] Error 2
[ 99%] Linking CXX executable ../../../../bin/netedit
[ 99%] Linking CXX shared library ../../../../bin/libsumocpp.so
[ 99%] Built target netedit
[ 99%] Built target libsumocpp
[ 99%] Linking CXX shared module ../../../../tools/libsumo/_libsumo.so
[ 99%] Built target libsumo
make: *** [Makefile:141: all] Error 2
![eoor](https://github.com/user-attachments/assets/6646d180-8b78-40d9-b760-4ff355f630e4)

**Comment by FinishFYP** [comment] 2024-07-16 09:41
I have the same problem with you. Have you resolve it?

**Comment by behrisch** [comment] 2024-07-16 12:41
It looks like you have anaconda on your system. Then it might be a duplicate of #14773. Please try the fix mentioned there: `rm ${CONDA_PREFIX}/lib/libffi.so.7`

**Comment by FinishFYP** [comment] 2024-07-17 01:58
> It looks like you have anaconda on your system. Then it might be a duplicate of #14773. Please try the fix mentioned there: `rm ${CONDA_PREFIX}/lib/libffi.so.7`. You could also try to disable anaconda while compiling sumo.

Thank you. I just followed your advice,  but it seems that my problem is a little different from @zhaotuo0815 's. The following is my the detailed:
![2024-07-17 09-58-24 的屏幕截图](https://github.com/user-attachments/assets/84b66e66-a819-47cd-ac63-3141554e4402)

**Comment by FinishFYP** [comment] 2024-07-18 03:08
> @FinishFYP If it is not related (e.g. because linking ffi is not involved), please open a new ticket and attach the complete build log. The image you've shown only contains warnings. Also please be aware that it is harder to support old versions like sumo 1.6.0, so check whether you can use a newer one.

Thank you for your reply. I have resolved this problem after I changed the sumo version from 1.6.0 to 1.8.0.

**Closed** 2024-07-18 06:04 UTC
Labels: os:linux
