### ISSUE TITLE
collision.action doesn't work

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#15257] opened 2024-07-23 01:48 UTC
I configured <collision.action value="teleport" /> in the sumocfg file, but it doesn't seem to work
![image](https://github.com/user-attachments/assets/b79c05df-2ba9-4d71-a610-ce1abea55191)
![image](https://github.com/user-attachments/assets/d3d879b1-9943-4c60-b3cd-90ad1b7fc60d)

**Comment by m-kro** [comment] 2024-07-23 06:24
This looks like a collision during changing lanes with the sublane model. Can you provide the scenario to reproduce it easily?

**Comment by zlh212** [comment] 2024-07-23 07:03
[suburb.zip](https://github.com/user-attachments/files/16344911/suburb.zip)
At around 220, there will be a collision

**Comment by zlh212** [comment] 2024-07-23 08:42
What does that mean? Does that collision happen because of step-length

**Comment by m-kro** [comment] 2024-07-23 18:04
No, it is just another issue which emerged from your sample data. I will look into your case during this week.

**Comment by namdre** [comment] 2024-07-30 10:23
It's a netconvert bug: The collision check doesn't work even when setting **--collisions.check-junctions** because the two connections are not marked as being in conflict in the .net.xml file.  Arguably, connections starting from the same edge and going to the same edge should not cross in any sane intersection design but netconvert should still flag the conflict.

**Closed** 2024-09-03 13:25 UTC
Labels: a:netconvert, c:sublane, bug
