### ISSUE TITLE
libtiff.5.dylib error in version 1.17.0

### ISSUE THREAD

**Issue by m-cak** [eclipse-sumo/sumo#13147] opened 2023-04-26 05:20 UTC
Hello everyone,

I updated to the latest version of SUMO (1.17.0). Since updating, my Python script (that I did not change in any way, the only thing that changed was that I went from SUMO 1.16.0 to 1.17.0) does not work properly. Once it gets to 'traci.start(...)' I get this (error) message (shown below) over and over again. I really need SUMO 1.17.0 for the '--personinfo-output' option.

Retrying in 1 seconds
dyld[6856]: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Referenced from: <DC609B96-2A76-324C-8F5E-76DCF43FFFAE> /usr/local/Cellar/sumo/1.17.0/bin/sumo
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/libtiff/4.5.0/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libtiff/4.5.0/lib/libtiff.5.dylib' (no such file), '/usr/local/Cellar/libtiff/4.5.0/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/traci/main.py:159: UserWarning: Could not connect to TraCI server using port 50113 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +

EDIT: I think I know where the problem is. I updated my macOS version simultaneously and the search for 'libtiff.5.dylib' that the traci.start() function initiates automatically fails because now it's 'libtiff.6.dylib' in macOS 13.3.1.

**SUMO-version: 1.17.0**

**operating system: macOS Ventura 13.3.1**

**Comment by angelobanse** [comment] 2023-04-26 07:28
Have you tried uninstalling and reinstalling SUMO?
```
brew uninstall sumo
brew autoremove
brew install sumo
```

**Comment by m-cak** [comment] 2023-04-26 09:08
@angelobanse 
Yes, I tried that already. Unfortunately, with no results.

**Comment by angelobanse** [comment] 2023-04-26 10:17
check with `brew doctor` if you get any warnings about unbrewed dylibs (residual files from older installations)

**Comment by m-cak** [comment] 2023-04-26 14:07
@angelobanse 
Also did not work. I manually changed 'libtiff.6.dylib' back to 'libtiff.5.dylib'. It works now, I do not know if there will be any other side effects though.

**Comment by aisiklar** [comment] 2023-05-16 10:01
@m-cak Hi, just saw this issue. I am having the same problem. I installed something with homebrew and I suppose it upgraded libTiff, too... So sumo broke down... Re-installed sumo with brew and yet the same problem continues...  When you say "manually changed", do you mean yo modified the file name, from ....6.dylib >> ....5.dylib ? 
Thanks.

**Comment by namdre** [comment] 2023-05-16 10:04
We've now had 3 reports on this so I don't think we can close this issue yet. @angelobanse do you suppose the problem is something to be fixed on the homebrew or something we should handle? If the former, do you see a way to escalate?

**Comment by angelobanse** [comment] 2023-05-16 10:11
@namdre let me look into this, and report back

**Comment by aisiklar** [comment] 2023-05-16 12:45
> 

Thanks.

**Comment by aisiklar** [comment] 2023-05-16 12:46
> That's exactly what I did and I haven't changed it back to '6'.

Ok, thanks..

**Comment by aisiklar** [comment] 2023-05-29 05:49
Hello, 

I have a weird situation. After changing the name of the lib (as @m-cak did), I did indeed could run the sumo.... But have not touched it much since that day due to other work... Anyway, the first time I ran the simulation was today (after this change)...
And now, my sumo results have changed... I cannot truly or with confidence say that this is the reason (yet I have not even touched my scripts) and to be frank I do not expect it but I just wanted to mention here if anyone else has seen this kind of problem... 
My problem is, in brief, I have 3 different simulations running with the same traffic deman (network, flow files etc)... The difference is the traffic lights (static vs adaptive), and the algorithm that I am running within the python script (using traci lib).
Before this change, my results for the 3 different simulation were the same and stabile... After this change, the first time I tried, it seems the results have changed... It is like the simulation gives different results now... But as I said, for the previous xxx times, the results did not vary, even a little.

I am still studying the condition, trying to understand and If i find any supportive or opposing thing I will write here, but I did want to ask kindly, If any of you had similar weird issues and I also kindly wanted to ask the maintainers and sumo devs if there is any kind of progress with the above issue...
Thanks for your support and for reading so far.
best, 
alptekin

**Comment by namdre** [comment] 2023-05-29 16:19
In principle the ranking could change due to changes in sumo though i would generally expect the adaptive light to beat a static controller. Which sumo versions was either result created with? If you can create 2 scenarios (preferably, reproducible without traci) where the ranking changes between version, please open up another ticket (and state the exact versions used).
Before you, do though, try running your scenarios with different seeds i.e. with runSeeds.py (https://sumo.dlr.de/docs/Tools/Misc.html#runseedspy) to ensure that the reversed ranking is stable and not an artefact of randomness.

**Comment by aisiklar** [comment] 2023-06-02 05:08
Hi, 
sorry for the late response. Nowadays I am tangled with some stuff.  
The version is the latest one, 1.17.0.  
The sims are run on the same sumo version. 

As said the results do not vary with time on the same version (ie the static sim run yesterday has the same result when run today), but between two versions it changed (static sim run on the prev. version was different.).
 I am not familiar with runSeeds.py, I will study/check it and try to return with a more appropriate findings. 

But speaking of my little exp :), I have seen the cases when static beats adaptive, not much, but yes there are some situations. I cannot say the core reason of course but it might be, when the traffic is quite light, the static might be doing better... sometimes. Anyway..

Do you wish me to return to previous version and do a comparison between the sims with same conditions (network, traffic etc) between two versions? (If so, I am not sure I know how to revert to prev version. I installed sumo with homebrew. I can check (in an appropriate time) but I am not sure whether this is what you mean. ) 

Would you kindly clarify that?
Thanks.

**Comment by namdre** [comment] 2023-06-02 05:11
if you can provide a scenario where static beats adaptive in 1.170. that would be enough.

**Comment by matthewdanepeavoy** [comment] 2023-09-10 13:05
Just experienced this same error as well. Have no idea what happened, (I tried to install Laravel Valet, it auto-updated brew and then could no longer run php commands) but changing libtiff.6.dylib to libtiff.5.dylib fixed the one error.

I had a matching error though where I had to change libavif.16.dylib to libavif.14.dylib and I'm back up and running now

**Comment by Skipe99** [comment] 2023-09-14 09:00
I also encountered the same problem:
httpd: Syntax error on line 183 of /opt/homebrew/etc/httpd/httpd.conf: Cannot load /opt/homebrew/opt/php@8.1/lib/httpd/modules/libphp.so into server: dlopen(/opt /homebrew/opt/php@8.1/lib/httpd/modules/libphp.so, 0x000A): Library not loaded: '/opt/homebrew/opt/libtiff/lib/libtiff.5.dylib'\n Referenced from: ' /opt/homebrew/Cellar/gd/2.3.3_4/lib/libgd.3.dylib'\n Reason: tried: '/opt/homebrew/opt/libtiff/lib/libtiff.5.dylib' (no such file) , '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file), '/opt/homebrew/Cellar/libtiff/4.5 .1/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' ( no such file)
It can't even start php or httpd, has anyone managed to solve this?

**Comment by Skipe99** [comment] 2023-09-14 21:15
Thanks for the reply, I had already tried but without success. I had to reinstall all versions of php and apache2 and that solved it

**Comment by aseevia** [comment] 2023-09-22 13:30
If you look at the symlinks in the folder more closely, you will find out that copying may actually better:
`cp libtiff.6.dylib libtiff.5.dylib`
The above fixed it for me.

**Comment by unkelhoebbi** [comment] 2023-11-03 17:19
For me `brew reinstall gd` did the job since the error was happening inside gd.

**Comment by ibrahimsaputra** [comment] 2023-11-07 21:50
> For me `brew reinstall gd` did the job since the error was happening inside gd.
 hi  i want to thank for you answer, this is work for me, and i want to ask you too, how did you know the error happen inside gd? while no such name in error path as gd, i'm new with mac

**Comment by unkelhoebbi** [comment] 2023-11-08 07:13
> > For me `brew reinstall gd` did the job since the error was happening inside gd.
> 
>  
> 
> hi  i want to thank for you answer, this is work for me, and i want to ask you too, how did you know the error happen inside gd? while no such name in error path as gd, i'm new with mac 

I don't have my console output anymore 😅 But I checked where the dependency originated from and for me this was in gd.

**Closed** 2023-11-08 07:51 UTC
Labels: c:build, os:mac
