### ISSUE TITLE
Vehicle body tilt

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#14847] opened 2024-05-10 08:11 UTC
为什么车辆会出现这种情况?
![image](https://github.com/eclipse-sumo/sumo/assets/62287281/824fb1b0-0ddd-4288-8d09-c805dc1082b9)

**Comment by m-kro** [comment] 2024-05-10 08:37
Please write your question in English. Do you use the option **--lanechange.duration**?

**Comment by namdre** [comment] 2024-05-13 07:46
duplicate of #14846

**Closed by namdre** 2024-05-13 07:46 UTC
Labels: duplicate, question, a:sumo
